name = "lustre_ui"
version = "0.6.0"
description = "A collection of components and design tokens for building Lustre apps."
target = "javascript"

licences = ["MIT"]
repository = { type = "github", user = "lustre-labs", repo = "lustre_ui" }
links = [
  { title = "Website", href = "https://lustre.build" },
  { title = "Sponsor", href = "https://github.com/sponsors/hayleigh-dot-dev" },
]

internal_modules = ["internals/*", "lustre/ui/internals"]
gleam = ">= 1.0.0"

[dependencies]
gleam_community_maths = ">= 1.1.0 and < 2.0.0"
gleam_stdlib = "~> 0.34"
lustre = "~> 4.0"

[dev-dependencies]
gleeunit = "~> 1.0"
lustre_dev_tools = ">= 1.3.3 and < 2.0.0"
